@echo off
:: ============================================================================
:: Agentium Voice Bridge Bootstrap
:: Auto-generated by docker-compose voice-autoinstall service.
:: Runs setup.ps1 silently and logs output to %USERPROFILE%\.agentium\bootstrap.log
:: ============================================================================
setlocal EnableDelayedExpansion

set LOG=%USERPROFILE%\.agentium\bootstrap.log
echo [%DATE% %TIME%] Bootstrap started >> "%LOG%"

:: REPO_ROOT is written in by the installer — do not edit this line manually
set REPO=AGENTIUM_REPO_ROOT

set SETUP=%REPO%\voice-bridge\setup.ps1

if not exist "%SETUP%" (
    echo [%DATE% %TIME%] ERROR: setup.ps1 not found at %SETUP% >> "%LOG%"
    echo.
    echo  Agentium voice bridge setup.ps1 was not found.
    echo  Expected location: %SETUP%
    echo.
    echo  Please run setup.ps1 manually from your repo:
    echo    powershell -ExecutionPolicy Bypass -File "^<repo^>\voice-bridge\setup.ps1"
    echo.
    pause
    exit /b 1
)

powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden ^
    -File "%SETUP%" >> "%LOG%" 2>&1

echo [%DATE% %TIME%] Bootstrap complete (exit %ERRORLEVEL%) >> "%LOG%"